[workspace]
authors = ["Rob Timpe <rtimpe@openteams.com>"]
channels = ["conda-forge", "nodefaults"]
name = "transformers"
platforms = [{ platform = "linux-64", cuda = "12" }]
version = "0.1.0"

[activation.env]
HF_HUB_CACHE = "/space_ssd/rtimpe/.cache/huggingface/hub/"

[dependencies]
python = "*"
pip = "*"
transformers = "*"
pytorch = "*"
accelerate = "*"
bitsandbytes = "*"